baseurl = "http://www.devcows.com/"
languageCode = "en-us"
title = "DevCows"
theme = "hugo-universal-theme"
MetaDataFormat = "yaml"
copyright = "Copyright (c) 2015 - 2016, DevCows; all rights reserved."

# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-57386726-1"

# Define the number of posts per page
paginate = 10

[params]
    viewMorePostLink     = "/blog/"
    author = "DevCows"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@devcows.com"

    about_us = "<p>We are specialized in Ruby on Rails, Django and Android development.</p><p>If you want to obtain more information about the team, please, feel free to <a href='/contact'>contact us</a>. We would love to hear from you.</p>"
    copyright = "Copyright (c) 2015 - 2016, DevCows; all rights reserved."
    date_format = "2006-01-02"
    logo = "media/devcows-logo.png"
    logo_small = "media/devcows-logo.png"
    address = """<p><strong><u>DevCows</u></strong>
        <br>Avda. Països Catalans, 28 B - local B
        <br>Sant Pere i Sant Pau
        <br>43007
        <br>Tarragona
        <br>
        <strong>Spain</strong>
      </p>
      """
    latitude = "41.133373"
    longitude = "1.246667"


[menu]

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog"
    weight     = 2

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact"
    weight     = 3

[social]
    github = "devcows"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to know more?"
    subtitle = "Whether you have a business idea or just want to know more about our offerings, we are willing to hear from you."
    link_url = "/contact"
    link_text = "Contact Us"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = ""

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"